"""initial classroom schema

Revision ID: 70ff7676e1bb
Revises:
Create Date: 2026-08-14 15:17:15.330032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ff7676e1bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('normalized_name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('game_model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_model_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('theoretical_rtp', sa.Float(), nullable=True),
    sa.Column('theoretical_hit_rate', sa.Float(), nullable=True),
    sa.Column('theoretical_variance', sa.Float(), nullable=True),
    sa.Column('calculation_method', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_model_id'], ['game_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_hash'),
    sa.UniqueConstraint('game_model_id', 'version_number')
    )
    with op.batch_alter_table('game_model_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_model_version_is_active'), ['is_active'], unique=False)

    op.create_table('play_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['game_model_version.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('play_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_play_session_player_id'), ['player_id'], unique=False)

    op.create_table('simulation_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('requested_spins', sa.Integer(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['game_model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.String(length=36), nullable=False),
    sa.Column('trial_number', sa.Integer(), nullable=False),
    sa.Column('spins_completed', sa.Integer(), nullable=False),
    sa.Column('total_wager_units', sa.Integer(), nullable=False),
    sa.Column('total_payout_units', sa.Integer(), nullable=False),
    sa.Column('ending_balance_units', sa.Integer(), nullable=False),
    sa.Column('max_drawdown_units', sa.Integer(), nullable=False),
    sa.Column('longest_losing_streak', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_run_id', 'trial_number')
    )
    with op.batch_alter_table('simulation_trial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_trial_simulation_run_id'), ['simulation_run_id'], unique=False)

    op.create_table('spin',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_token', sa.String(length=64), nullable=False),
    sa.Column('play_session_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('stake_units', sa.Integer(), nullable=False),
    sa.Column('payout_units', sa.Integer(), nullable=False),
    sa.Column('board_json', sa.JSON(), nullable=False),
    sa.Column('evaluation_json', sa.JSON(), nullable=False),
    sa.Column('feature_state_json', sa.JSON(), nullable=False),
    sa.Column('rng_audit_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('payout_units >= 0'),
    sa.CheckConstraint('stake_units > 0'),
    sa.ForeignKeyConstraint(['model_version_id'], ['game_model_version.id'], ),
    sa.ForeignKeyConstraint(['play_session_id'], ['play_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_token')
    )
    with op.batch_alter_table('spin', schema=None) as batch_op:
        batch_op.create_index('ix_spin_session_created', ['play_session_id', 'created_at'], unique=False)

    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('spin_id', sa.String(length=36), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount_units', sa.Integer(), nullable=False),
    sa.Column('balance_after_units', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("entry_type in ('ALLOCATION','WAGER','PAYOUT','ADJUSTMENT','RESET')"),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['spin_id'], ['spin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entry_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entry_spin_id'), ['spin_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entry_spin_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entry_player_id'))

    op.drop_table('ledger_entry')
    with op.batch_alter_table('spin', schema=None) as batch_op:
        batch_op.drop_index('ix_spin_session_created')

    op.drop_table('spin')
    with op.batch_alter_table('simulation_trial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_trial_simulation_run_id'))

    op.drop_table('simulation_trial')
    op.drop_table('simulation_run')
    with op.batch_alter_table('play_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_play_session_player_id'))

    op.drop_table('play_session')
    with op.batch_alter_table('game_model_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_model_version_is_active'))

    op.drop_table('game_model_version')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_normalized_name'))

    op.drop_table('player')
    op.drop_table('game_model')
    # ### end Alembic commands ###
